### ISSUE TITLE
Unknown function: sniphpets#settings

### ISSUE THREAD

**Issue by henkloke** [sniphpets/sniphpets-common#1]
if installed with vim-plug I get the error:
/sniphpets-common/plugin/sniphpets_common.vim:
line    8:
E117: Unknown function: sniphpets#settings
E15: Invalid expression: sniphpets#settings('common_disable_shortcuts', 0) == 0

**Comment by voronkovich** [comment]
@henkloke, I think, you should install the https://github.com/sniphpets/sniphpets library.

**Comment by henkloke** [comment]
Sorry missed that.
All working OK now
